CREATE TABLE "users" (
  "user_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar NOT NULL,
  "Lastname" varchar NOT NULL,
  "displayname" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL
);